"""Stable machine-readable error codes shared across application boundaries."""

from __future__ import annotations

from enum import StrEnum


class ErrorCode(StrEnum):
    """Public error identifiers; values are API contracts once released."""

    REQUEST_VALIDATION_FAILED = "REQUEST_VALIDATION_FAILED"
    AUTH_REQUIRED = "AUTH_REQUIRED"
    AUTH_SETUP_REQUIRED = "AUTH_SETUP_REQUIRED"
    AUTH_OWNER_SETUP_DISABLED = "AUTH_OWNER_SETUP_DISABLED"
    AUTH_OWNER_ALREADY_INITIALIZED = "AUTH_OWNER_ALREADY_INITIALIZED"
    AUTH_USER_NOT_FOUND = "AUTH_USER_NOT_FOUND"
    AUTH_INVALID_PASSWORD = "AUTH_INVALID_PASSWORD"
    AUTH_ACCOUNT_DISABLED = "AUTH_ACCOUNT_DISABLED"
    AUTH_INVALID_CREDENTIALS = "AUTH_INVALID_CREDENTIALS"
    AUTH_INVALID_SETUP_CREDENTIAL = "AUTH_INVALID_SETUP_CREDENTIAL"
    AUTH_INVALID_CURRENT_PASSWORD = "AUTH_INVALID_CURRENT_PASSWORD"
    AUTH_ACCOUNT_REQUIRED = "AUTH_ACCOUNT_REQUIRED"
    AUTH_SESSION_REQUIRED = "AUTH_SESSION_REQUIRED"
    AUTH_PERMISSION_DENIED = "AUTH_PERMISSION_DENIED"
    AUTH_OWNER_ACCOUNT_PROTECTED = "AUTH_OWNER_ACCOUNT_PROTECTED"
    AUTH_OWNER_ROLE_ASSIGNMENT_FORBIDDEN = "AUTH_OWNER_ROLE_ASSIGNMENT_FORBIDDEN"
    AUTH_ADMIN_MANAGEMENT_NOT_DELEGATED = "AUTH_ADMIN_MANAGEMENT_NOT_DELEGATED"
    USER_USERNAME_ALREADY_EXISTS = "USER_USERNAME_ALREADY_EXISTS"
    SESSION_NOT_FOUND = "SESSION_NOT_FOUND"
    SESSION_ID_CONFLICT = "SESSION_ID_CONFLICT"
    CONFIG_INVALID = "CONFIG_INVALID"
    AUTH_UNAVAILABLE = "AUTH_UNAVAILABLE"
    TOOL_CONFIRMATION_UNAVAILABLE = "TOOL_CONFIRMATION_UNAVAILABLE"
    LLM_ERROR = "LLM_ERROR"
    INTERNAL_ERROR = "INTERNAL_ERROR"
